#!/usr/bin/env python

import sys, os, re
from subprocess import check_output

# Collect the parameters
commit_msg_filepath = sys.argv[1]

# Figure out which branch we're on
branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()
print "commit-msg: On branch '%s'" % branch

message_starts = "MED-"

# Check the commit message if we're on an issue branch
with open(commit_msg_filepath, 'r') as f:
    content = f.read()
    if not content.startswith(message_starts):
    	print "commit-msg: ERROR! The commit message must start with '%s'" % message_starts
        sys.exit(1)
